<?php

namespace Sevaske\PayfortApi\Enums;

enum PayfortMessageEnum: string
{
    case Success = '000'; // Success.
    case MissingParameter = '001'; // Missing parameter.
    case InvalidParameterFormat = '002'; // Invalid parameter format.
    case PaymentOptionNotAvailable = '003'; // Payment option is not available for this merchant’s account.
    case InvalidCommand = '004'; // Invalid command.
    case InvalidAmount = '005'; // Invalid amount.
    case TechnicalProblem = '006'; // Technical problem.
    case DuplicateOrderNumber = '007'; // Duplicate order number.
    case SignatureMismatch = '008'; // Signature mismatch.
    case InvalidMerchantIdentifier = '009'; // Invalid merchant identifier.
    case InvalidAccessCode = '010'; // Invalid access code.
    case OrderNotSaved = '011'; // Order not saved.
    case CardExpired = '012'; // Card expired.
    case InvalidCurrency = '013'; // Invalid currency.
    case InactivePaymentOption = '014'; // Inactive payment option.
    case InactiveMerchantAccount = '015'; // Inactive merchant account.
    case InvalidCardNumber = '016'; // Invalid card number.
    case OperationNotAllowedByAcquirer = '017'; // Operation not allowed by the acquirer.
    case OperationNotAllowedByProcessor = '018'; // Operation not allowed by processor.
    case InactiveAcquirer = '019'; // Inactive acquirer.
    case ProcessorIsInactive = '020'; // Processor is inactive.
    case PaymentOptionDeactivatedByAcquirer = '021'; // Payment option deactivated by acquirer.
    case CurrencyNotAcceptedByAcquirer = '023'; // Currency not accepted by acquirer.
    case CurrencyNotAcceptedByProcessor = '024'; // Currency not accepted by processor.
    case ProcessorIntegrationSettingsMissing = '025'; // Processor integration settings are missing.
    case AcquirerIntegrationSettingsMissing = '026'; // Acquirer integration settings are missing.
    case InvalidExtraParameters = '027'; // Invalid extra parameters.
    case InsufficientFunds = '029'; // Insufficient funds.
    case AuthenticationFailed = '030'; // Authentication failed.
    case InvalidIssuer = '031'; // Invalid issuer.
    case InvalidParameterLength = '032'; // Invalid parameter length.
    case ParameterValueNotAllowed = '033'; // Parameter value not allowed.
    case OperationNotAllowed = '034'; // Operation not allowed.
    case OrderCreatedSuccessfully = '035'; // Order created successfully.
    case OrderNotFound = '036'; // Order not found.
    case MissingReturnUrl = '037'; // Missing return URL.
    case TokenServiceInactive = '038'; // Token service inactive.
    case NoActivePaymentOptionFound = '039'; // No active payment option found.
    case InvalidTransactionSource = '040'; // Invalid transaction source.
    case OperationAmountExceedsAuthorizedAmount = '042'; // Operation amount exceeds the authorized amount.
    case InactiveOperation = '043'; // Inactive Operation.
    case TokenNameDoesNotExist = '044'; // Token name does not exist.
    case ChannelNotConfigured = '046'; // Channel is not configured for the selected payment option.
    case OrderAlreadyProcessed = '047'; // Order already processed.
    case OperationAmountExceedsCapturedAmount = '048'; // Operation amount exceeds captured amount.
    case OperationNotValidForPaymentOption = '049'; // Operation not valid for this payment option.
    case MerchantPerTransactionLimitExceeded = '050'; // Merchant per transaction limit exceeded.
    case TechnicalError = '051'; // Technical error.
    case ConsumerNotInOlpDatabase = '052'; // Consumer is not in OLP database.
    case MerchantNotFoundInOlpEngineDb = '053'; // Merchant is not found in OLP Engine DB.
    case TransactionCannotBeProcessedNow = '054'; // Transaction cannot be processed at this moment.
    case OlpIdAliasNotValid = '055'; // OLP ID Alias is not valid. Please contact your bank.
    case OlpIdAliasDoesNotExist = '056'; // OLP ID Alias does not exist. Please enter a valid OLP ID Alias.
    case TransactionAmountExceedsDailyLimit = '057'; // Transaction amount exceeds the daily transaction limit.
    case TransactionAmountExceedsPerTransactionLimit = '058'; // Transaction amount exceeds the per transaction limit.
    case MerchantNameAndSadadIdDoNotMatch = '059'; // Merchant Name and SADAD Merchant ID do not match.
    case IncorrectOlpPassword = '060'; // The entered OLP password is incorrect. Please provide a valid password.
    case TokenCreated = '062'; // Token has been created.
    case TokenUpdated = '063'; // Token has been updated.
    case ThreeDSecureCheckRequested = '064'; // 3D Secure check requested.
    case TransactionWaitingForCustomerAction = '065'; // Transaction waiting for customer’s action.
    case MerchantReferenceAlreadyExists = '066'; // Merchant reference already exists.
    case DynamicDescriptorNotConfigured = '067'; // Dynamic Descriptor not configured for selected payment option.
    case SdkServiceInactive = '068'; // SDK service is inactive.
    case MappingNotFoundForErrorCode = '069'; // Mapping not found for the given error code.
    case DeviceIdMismatch = '070'; // device_id mismatch.
    case FailedToInitiateConnection = '071'; // Failed to initiate connection.
    case TransactionCancelledByConsumer = '072'; // Transaction has been cancelled by the consumer.
    case InvalidRequestFormat = '073'; // Invalid request format.
    case TransactionFailed = '074'; // Transaction failed.
    case TransactionFailedDuplicate = '075'; // Transaction failed.
    case TransactionNotFoundInOlp = '076'; // Transaction not found in OLP.
    case ErrorTransactionCodeNotFound = '077'; // Error transaction code not found.
    case FailedToCheckFraudScreen = '078'; // Failed to check fraud screen.
    case TransactionChallengedByFraudRules = '079'; // Transaction challenged by fraud rules.
    case InvalidPaymentOption = '080'; // Invalid payment option.
    case InactiveFraudService = '082'; // Inactive fraud service.
    case UnexpectedUserBehavior = '083'; // Unexpected user behavior.
    case TransactionAmountOutOfRange = '084'; // Transaction amount is either bigger than maximum or less than minimum amount accepted for the selected plan.
    case InstallmentPlanNotConfigured = '086'; // Installment plan is not configured for Merchant account.
    case CardBinDoesNotMatchIssuerBank = '087'; // Card BIN does not match accepted issuer bank.
    case TokenNameNotCreatedForTransaction = '088'; // Token name was not created for this transaction.
    case FailedToRetrieveDigitalWalletDetails = '089'; // Failed to retrieve digital wallet details.
    case TransactionInReview = '090'; // Transaction in review.
    case InvalidIssuerCode = '092'; // Invalid issuer code.
    case ServiceInactive = '093'; // service inactive.
    case InvalidPlanCode = '094'; // Invalid Plan Code.
    case InactiveIssuer = '095'; // Inactive Issuer.
    case InactivePlan = '096'; // Inactive Plan.
    case OperationNotAllowedForService = '097'; // Operation not allowed for service.
    case InvalidOrExpiredCallId = '098'; // Invalid or expired call_id.
    case FailedToExecuteService = '099'; // Failed to execute service.
    case InvalidExpiryDate = '100'; // Invalid expiry date.
    case BillNumberNotFound = '101'; // Bill number not found.
    case ApplePayOrderExpired = '102'; // Apple Pay order has been expired.
    case DuplicateSubscriptionId = '103'; // Duplicate subscription ID.
    case NoPlansValidForRequest = '104'; // No plans valid for request.
    case InvalidBankCode = '105'; // Invalid bank code.
    case InactiveBank = '106'; // Inactive bank.
    case InvalidTransferDate = '107'; // Invalid transfer_date.
    case ContradictingParameters = '110'; // Contradicting parameters, please refer to the integration guide.
    case ServiceNotApplicableForPaymentOption = '111'; // Service not applicable for payment option.
    case ServiceNotApplicableForPaymentOperation = '112'; // Service not applicable for payment operation.
    case ServiceNotApplicableForECommerceIndicator = '113'; // Service not applicable for e-commerce indicator.
    case TokenAlreadyExist = '114'; // Token already exist.
    case ExpiredInvoicePaymentLink = '115'; // Expired invoice payment link.
    case InactiveNotificationType = '116'; // Inactive notification type.
    case InvoicePaymentLinkAlreadyProcessed = '117'; // Invoice payment link already processed.
    case OrderBounced = '118'; // Order bounced.
    case RequestDropped = '119'; // Request dropped.
    case PaymentLinkTermsAndConditionsNotFound = '120'; // Payment link terms and conditions not found.
    case CardNumberNotVerified = '121'; // Card number is not verified.
    case InvalidDateInterval = '122'; // Invalid date interval.
    case MaxAttemptsExceeded = '123'; // You have exceeded the maximum number of attempts.
    case AccountSuccessfullyCreated = '124'; // Account successfully created.
    case InvoiceAlreadyPaid = '125'; // Invoice already paid.
    case DuplicateInvoiceId = '126'; // Duplicate invoice ID.
    case MerchantReferenceNotGeneratedYet = '127'; // Merchant reference is not generated yet.
    case ReportStillPending = '128'; // The generated report is still pending, you can’t download it now.
    case DownloadedReportQueueFull = '129'; // “Downloaded report” queue is full. Wait till its empty again.
    case SearchResultsExceededMaxRecords = '134'; // Your search results have exceeded the maximum number of records.
    case BatchFileValidationFailed = '136'; // The Batch file validation is failed.
    case InvalidBatchFileExecutionDate = '137'; // Invalid Batch file execution date.
    case BatchFileStillUnderValidation = '138'; // The Batch file still under validation.
    case BatchFileStillUnderProcessing = '140'; // The Batch file still under processing.
    case BatchReferenceDoesNotExist = '141'; // The Batch reference does not exist.
    case BatchFileHeaderInvalid = '142'; // The Batch file header is invalid.
    case InvalidBatchFile = '144'; // Invalid Batch file.
    case BatchReferenceAlreadyExists = '146'; // The Batch reference is already exist.
    case BatchProcessRequestReceived = '147'; // The Batch process request has been received.
    case BatchFileWillBeProcessed = '148'; // Batch file will be processed.
    case PaymentLinkRequestIdNotFound = '149'; // Payment link request id not found.
    case PaymentLinkAlreadyOpen = '150'; // Payment link is already open.
    case ThreeDsIdDoesNotExist = '151'; // 3ds_id does not exist.
    case ThreeDsVerificationMismatch = '152'; // 3Ds verification doesn’t match the request details.
    case MaxUploadRetriesReached = '154'; // You have reached the maximum number of upload retries.
    case UploadRetriesNotConfigured = '155'; // The upload retries is not configured.
    case MinAmountNotReachedForService = '181'; // You didn’t reach the minimum amount for this service.
    case MaxAmountExceededForService = '221'; // You exceeded the maximum amount for this service.
    case OperationNotPermittedForMerchant = '225'; // This operation is not permitted for merchant to use.
    case OperationNotAllowedOrderNotConfirmed = '662'; // Operation not allowed. The specified order is not confirmed yet.
    case TransactionDeclined = '666'; // Transaction declined.
    case PurchaseAmountMoreThanCustomerLimit = '746'; // Purchase amount is more than the customer limit
    case InsufficientWalletBalance = '747'; // Insufficient Wallet Balance
    case ParameterMismatch = '748'; // PARAMETER_MISMATCH — Send OTP and purchase request parameters do not match.
    case TransactionClosed = '773'; // Transaction closed.
    case TransactionProcessedButNoConfirmation = '777'; // The transaction has been processed, but failed to receive confirmation.
    case SessionTimedOut = '778'; // Session timed-out.
    case TransformationError = '779'; // Transformation error.
    case TransactionNumberTransformationError = '780'; // Transaction number transformation error.
    case MessageOrResponseCodeTransformationError = '781'; // Message or response code transformation error.
    case InstallmentsServiceInactive = '783'; // Installments service inactive.
    case TransactionStillProcessing = '784'; // Transaction still processing you can’t make another transaction.
    case TransactionBlockedByFraudCheck = '785'; // Transaction blocked by fraud check.
    case FailedToAuthenticateUser = '787'; // Failed to authenticate the user.
    case InvalidBillNumber = '788'; // Invalid bill number.
    case ExpiredBillNumber = '789'; // Expired bill number.
    case InvalidBillTypeCode = '790'; // Invalid bill type code.
    case MinTimeBetweenOtpAttempts = '983'; // Minimum time between two One Time Password attempt is 60 seconds.
}
